language: ruby
rvm:
- 1.9.3
- 2.1
- ruby-head
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake

before_deploy:
- cp config/database.openshift.yml config/database.yml

deploy:
  provider: openshift
  user: helge.spieker@smail.inf.h-brs.de
  password:
    secure: SOUrarjMyVFW2cRQW2+gBdwfHazezl4bmciesWjF6xn0Onaug+ZgbEGB4VZ9xDYQ8cm0d3m9ROy07pKu6jE280Xucnqb9TBhz/Ne5LIcogxy9Ewr3Pc2g3OMZtihc0msqLf0vJuz7W7MGSq/zJtcUer4Z+iVFgJOdSqRl3xv5Cc=
  domain: bookwriter
  app:
    master: stable
    development: testing
  on:
    repo: team-sb/bookwriter
    rvm: 1.9.3