language: ruby
rvm:
- 1.9.3
- 2.1
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_deploy:
- cp config/database.openshift.yml config/database.yml
deploy:
  provider: openshift
  user: helge.spieker@smail.inf.h-brs.de
  password:
    secure: Lqfo92x8F2xajELJQdSBfv5dwuuSiOYfRgvh8pEFDbWqBMGwLHuqX3IprTUqX8j9Z5GHXnrdSpNF54smR1cvLwxdaWaRa5U7xMGEdzwcduDf12gcT5bBvTYMs5sepkmsVSehFC3Ck0S9e07ZgZRExtEbsFopViYdcwtUsTrQIFU=
  app:
    master: stable
    development: testing
  domain: bookwriter
  on:
    rvm: 1.9.3
    repo: team-sb/bookwriter
