development:
  adapter: postgresql
  database: bookwriter_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bookwriter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bookwriter_production
  pool: 5
  timeout: 5000